### ISSUE TITLE
Lack of examples

### ISSUE THREAD

**Issue by davidjcannon** [chinaman3928/FFDEditor#1]
It's hard to tell how to do a lot of things in this program. The biggest issue I'm having is with enchants. How do you enchant an item? The example given isn't helpful. I'd like to see an example command line.

From what I'm given I've tried
%VIT
%VIT + 15
And similar

Nothing seems to work, I'd love to use this.

**Comment by chinaman3928** [comment]
`Enter as many as you want (ex. '[value / '-' to remove] x y z')`

is the prompt. For example, to give the item 50% damage, strength, and HP, you'd do `50 %DMG %STR %HP`. Note this overrides the current values and is not additive. To remove knockback, `- KNOCKBACK`.

Thanks for the feedback. I'm working on moving the editor online for a user-friendlier GUI.
